# Loads default set of integrations. Do not remove.
default_config:
bluetooth:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifiers.yaml
alert: !include alerts.yaml

# Enable HTTPS
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#==============================================================================
# Recorder settings
#   - Use MariaDB
#==============================================================================
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 91 # 3 months (default 10 days)
  auto_purge: true
  exclude:
    # explicit entity exclusion using full entity_id (no wildcard)
    # entities:
    #   - entity_id
    # wildcard patterns
    entity_globs:
      - sensor.*_battery_level

#==============================================================================
# Logger settings
#==============================================================================
logger:
  # The next line sets the default logging level, for all python modules.
  # It seems "recommended" to set it to avoid too much logging.
  default: warning
  logs:
    zigpy: warning
    zigpy.zcl: warning
    zigpy_znp: warning
    zigpy.quirks: warning
    zhaquirks: warning
    homeassistant.components.zha: info

#==============================================================================
# Enable Prometheus integration
#==============================================================================
prometheus:
  requires_auth: false

#==============================================================================
# ZHA Configuration
#==============================================================================
zha:
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      extra_providers:
        # Use the unofficial Zigbee2MQTT OTA updates repository
        - type: z2m
          url: https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/index.json

#==============================================================================
# Home Assistant settings
#==============================================================================
homeassistant:
  packages: !include_dir_named packages

  # Customizations
  customize:
    sensor.plant_sensor_1_soil_moisture:
      device_class: moisture
    sensor.garden_raspberries_soil_moisture:
      device_class: moisture
