substitutions:
  name: konnected-8cf378
  friendly_name: Garage Door Opener 8cf378
packages:
  konnected.garage-door-gdov2-s: github://konnected-io/konnected-esphome/garage-door-GDOv2-S.yaml@master
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: IeDWVikIx1fPUjZ/1VJegkBdLwN3wgBy6u2fJWJHoEM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
