substitutions:
  name: apollo-air-1-2e0374
  friendly_name: Apollo AIR-1 2e0374
#packages:
#  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1_Factory.yaml
packages:
  ApolloAutomation.AIR-1: # name of package/project
    url: https://github.com/ApolloAutomation/AIR-1 # url of the repository
    ref: main # branch, tag or commit SHA
    files: [Integrations/ESPHome/AIR-1_BLE.yaml] # Path to config from base repo URL
    refresh: 1min # how often to sync updates from the remote url

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: J69h3V6H9Fa0pur93RC1wW5b7Wfgzvoenj/jzIvTupo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: sen5x
    id: !extend sen55
    update_interval: 5s