substitutions:
  name: konnected-8cf378
  friendly_name: Garage Door
  garage_door_close_warning_duration: 10s 
packages:
  konnected.garage-door-gdov2-s: github://konnected-io/konnected-esphome/garage-door-GDOv2-S.yaml@master
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: P6APXSyf7ivLgOiHYgLFxjmu5ZmSJNMbY6avb/oqdZM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
