###############################################################################
# TVOC Baseline Watchdog Package for Home Assistant
# Filename: airthings_wave_plus_tvoc_baseline_drift.yaml
# Detects when the Airthings Wave Plus VOC sensor's 7-day baseline
# has likely drifted upward and notifies for a fresh-air reset.
###############################################################################

###############################################################################
# 1. 8-day rolling minimum of Airthings Wave Plus TVOC Index (Statistics Platform)
###############################################################################
sensor:
  - platform: statistics
    entity_id: sensor.iaq_airthings_wave_plus_tvoc_index
    name: "IAQ Airthings Wave Plus TVOC Index 8d Min"
    state_characteristic: value_min
    max_age:
      days: 8 # covers the full 7-day baseline period + margin
    sampling_size: 2000 # ~5-min sampling ⇒ ≈2304 pts / 8 days; 2000 is OK
    unique_id: "c13b8438-1992-4f71-8720-81935b5548e5"

###############################################################################
# 2. Binary sensor with hysteresis (Threshold Platform)
###############################################################################
binary_sensor:
  - platform: threshold
    name: "IAQ Airthings Wave Plus TVOC Baseline Drifted"
    entity_id: sensor.iaq_airthings_wave_plus_tvoc_index_8d_min
    device_class: problem
    upper: 100 # “clean air” upper limit in ppb-eq
    hysteresis: 20 # ON if >120   ; OFF if <80  (ppb-eq)

###############################################################################
# 3. Alert until recalibration
###############################################################################
alert:
  # Home temperature critical Alert
  iaq_airthings_wave_plus_tvoc_baseline_drift:
    name: "IAQ Airthings Wave Plus TVOC baseline drift warning"
    title: "Airthings TVOC Sensor Drift Detected"
    message: >-
      TVOC Index ≥ 100 ppb-eq for 7 days. Expose sensor to fresh air
      for ~10 minutes to reset baseline.
    done_message: "clear_notification"
    entity_id: binary_sensor.iaq_airthings_wave_plus_tvoc_baseline_drifted
    state: "on"
    repeat:
      - 1440 # one day
      - 1440
      - 2880 # two days
    skip_first: false
    can_acknowledge: false
    data:
      group: "system"
      tag: "airthings_drift_notification"
    notifiers:
      - group_system_administrators
